name: Rails test
description: Run Rails tests

inputs:
  token:
    description: Github personal access token (PAT) to clone other private repos
    required: false

  command:
    description: Command to run tests
    required: false
    default: bundle exec rails test

runs:
  using: docker
  # https://pkgs.alpinelinux.org/packages?name=ruby&branch=v3.14&arch=x86_64
  image: docker://voormedia/ruby-build:3.14

  env:
    RAILS_ENV: test
    DISABLE_SPRING: 1

  args:
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
    - git config --global url."https://oauth2:${{ inputs.token }}@github.com/".insteadOf "git@github.com:"
    - bundle config --global silence_root_warning true
    - bundle install
    - bundle exec rails db:create
    - if [ -f "db/structure.sql" ]; then bundle exec rails db:structure:load; else bundle exec rails db:schema:load; fi
    - ${{ inputs.command }}

# Add cache step
steps:
  - name: Cache bundle and assets
    uses: actions/cache@v3
    with:
      path: vendor/bundle
      key: ${{ runner.os }}-rails-${{ hashFiles('**/Gemfile.lock') }}
      restore-keys: |
        ${{ runner.os }}-rails-
