name: Rails test
description: Run Rails lints & tests
runs:
  using: docker
  image: Dockerfile
  args:
    - |
      ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
      bundle install
      bundle exec rails db:create db:structure:load
      bundle exec rails test
