name: Rails test
description: Run Rails lints & tests
runs:
  using: docker
  image: Dockerfile
  args: - |
    bundle install
    bundle exec rails db:create db:structure:load
    bundle exec rails test
