name: Rails test
description: Run Rails tests

inputs:
  token:
    description: Github personal access token (PAT) to clone other private repos
    required: false

  setup:
    description: Setup command to run before tests
    required: false
    default: echo

  command:
    description: Command to run tests
    required: false
    default: bundle exec rails test

runs:
  using: docker
  # https://pkgs.alpinelinux.org/packages?name=ruby&branch=v3.20&arch=x86_64
  # Point to older image for now because newer versions of Ruby cause issues with custom methods.
  image: docker://voormedia/ruby-build:3.20@sha256:377f814151d44e17d6854f67fe50630118afedb4e139b77bcb9f5abf909beb00

  env:
    RAILS_ENV: test
    DISABLE_SPRING: 1

  args:
    - ${{ inputs.setup }}

    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
    - git config --global url."https://${{ inputs.token }}@github.com/".insteadOf "git@github.com:"

    # Install dependencies.
    - bundle config --global silence_root_warning true
    - bundle install --jobs 8 --retry 3

    # Run rubocop if configured.
    # TODO: Extract into separate action? If so, make sure we need to run bundle only once!
    - if [ -f ".rubocop.yml" ]; then bundle exec rubocop; fi

    # Create test database.
    - bundle exec rails db:create

    # Load db structure from SQL or Ruby file.
    - if [ -f "config/sequel.rb" ]; then bundle exec rails db:structure:load; else bundle exec rails db:schema:load; fi

    # Run tests.
    - ${{ inputs.command }}
