name: Rails test
description: Run Rails tests

inputs:
  token:
    description: Github personal access token (PAT) to clone other private repos
    required: false

  command:
    description: Command to run tests
    required: false
    default: rails test

runs:
  using: docker
  # https://pkgs.alpinelinux.org/packages?name=ruby&branch=v3.14&arch=x86_64
  image: docker://voormedia/ruby-build:3.16

  env:
    RAILS_ENV: test
    DISABLE_SPRING: 1

  args:
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
    - git config --global url."https://oauth2:${{ inputs.token }}@github.com/".insteadOf "git@github.com:"

    # Install dependencies.
    - bundle config --global silence_root_warning true
    - bundle install

    # Run rubocop if configured.
    - if [ -f ".rubocop.yml" ]; then bundle exec rubocop; fi

    # Create test database.
    - bundle exec rails db:create

    # Load db structure from SQL or Ruby file.
    - if [ -f "db/structure.sql" ]; then bundle exec rails db:structure:load; else bundle exec rails db:schema:load; fi

    # Run tests.
    - bundle exec ${{ inputs.command }}
