name: Rails test
description: Run Rails lints & tests
runs:
  using: docker
  image: docker://voormedia/ruby-build:3.16

  env:
    RAILS_ENV: test
    DISABLE_SPRING: 1
    BUNDLE_SILENCE_ROOT_WARNING: 1

  entrypoint: |
    bundle install &&
    bundle exec rails db:create db:structure:load &&
    bundle exec rails test
